name: Gas Notification

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '00 00 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install bs4
        pip install requests
        pip install datetime
        pip install schedule
        pip install python-dotenv

    - name: Create dot env file
      run: |
        touch .env
        echo "LINE_TOKEN=${{ 'DC9x4EPqbGFFm6xuNGYe7wlmfYM57yUvLBW7KAYjecV' }}" >> .env
    - name: Gas_Notify.py
      run: |
        python Gas_Notify.py
        timeout-minutes: 10
    # - run: sleep 30
    - name: Commit and Push
      run: |
        git config user.name "renshimosawa"
        git config user.email "polaris2760@gmail.com"
        git add .
        git commit -m "Commit Message"
        git pull
        git push origin master