name: Gas Notification

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '00 00 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install bs4
        pip install requests
        pip install datetime
        pip install schedule
        pip install python-dotenv

    - name: Create dot env file
      run: |
        touch .env
        echo "LINE_TOKEN=${{ 'rwKoFPlpAoJFy3z1WHAWMoARyBFd9pqo7iCG9XxEoRy' }}" >> .env
        
    -name: Early exit
      run: exit_with_success # I want to know what command I should write here
        if: true
      -run: foo
      -run: python Gas_Notify.py