name: Gas Notification

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install bs4
        pip install requests
        pip install datetime
        pip install schedule
        pip install python-dotenv
    
    - name: Create dot env file
      run: |
        touch .env
        echo "LINE_TOKEN_1=${{ 'sHNHa4NZnALtXkYWcqRbcBQBaR15xQtZoUhGsgTc7vR' }}" >> .env
        echo "LINE_TOKEN_2=${{ '2Hc5PTFUAx3PRpdusxY1DHCAnrdSHnc9J34u0tuROkI' }}" >> .env
    - name: Gas_Notify_H.py
      run: |
        python Gas_Notify_H.py
    - name: Gas_Notify.py
      run: |
        python Gas_Notify.py
        python Gas_Notify_H.py
    - name: Commit and Push
      run: |
        git config user.name "renshimosawa"
        git config user.email "polaris2760@gmail.com"
        git add .
        git commit -m "Commit Message"
        git pull
        git push origin master