name: Gas Notification

on:
  push:
      branches: [ main ]
  schedule:
    - cron: '01 00 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install bs4
        pip install time
        pip install requests
        pip install datetime
        pip install setting
        pip install schedule
    - name: Gas_Notify.py
      run: |
        python Gas_Notify.py