name: Gas Notification

on:
  schedule:
    - cron: '45 22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install bs4
        pip install requests
        pip install datetime
        pip install schedule
        pip install python-dotenv
    
    - name: Create dot env file
      run: |
        touch .env
        echo "LINE_TOKEN_F=${{ 'sHNHa4NZnALtXkYWcqRbcBQBaR15xQtZoUhGsgTc7vR' }}" >> .env
        echo "LINE_TOKEN_Y=${{ 'gDy19jFvD7uMVdRoZQVGlOcOQCzKYA9a1HGBUznOho1' }}" >> .env
        echo "LINE_TOKEN_N=${{ 'PS3UDNmzgTeXyUeEYLaVQ0RLOSUoejcx0sbORNGb4Fe' }}" >> .env
        echo "LINE_TOKEN_GM=${{ 'qvaFwcp4Mh2Bw7wUYKUYnFADX6mjpVctfzEPKjbLbEL' }}" >> .env
    - name: Notify_H.py
      run: |
        python Gas_Notify_H.py &
        python Gas_Notify_N.py &
        python Gas_Notify_GM.py &
        python Gas_Notify.py &